# Use Go official image
FROM golang:1.21

# Set working directory
WORKDIR /app

# Copy Go files
COPY . .

# Download dependencies
RUN go mod init backend && go mod tidy

# Build Go application
RUN go build -o backend

# Expose backend API port
EXPOSE 5000

# Run the backend server
CMD ["./backend"]
